### ISSUE TITLE
 Add a "Kubuntu" Logo and Kubuntu for OS info to FastFetch

### ISSUE THREAD

**Issue by Danik2343** [LinusDierheimer/fastfetch#150]
# Current state: fastfetch on "Kubuntu" show Linux "Ubuntu" logo

# Wanted state: fastfetch on "Kubuntu" show "Kubuntu" logo and Fastfetch writes OS: "Kubuntu" instead of OS: "Ubuntu"

# Why the change is sensible: Updating/Adding Fastfetch logos\information
P.S Logo and information about OS on neofetch: 
![изображение](https://user-images.githubusercontent.com/38865696/164937120-72e01fb3-3b05-491f-b1f0-e081c197de7e.png)

**Comment by Danik2343** [comment]
![изображение](https://user-images.githubusercontent.com/38865696/164938081-f70ade5b-9c9e-4bba-9bd6-7d831df4e32e.png)
Fastetch now

**Comment by LinusDierheimer** [comment]
Can you please post the content of `/etc/os-release`?

**Comment by LinusDierheimer** [comment]
Done. If it doesn't work, ill need the content of `/etc/os-release`.

**Comment by Danik2343** [comment]
[os-release(Kubuntu 22.04 LTS).tar.gz](https://github.com/LinusDierheimer/fastfetch/files/8556638/os-release.Kubuntu.22.04.LTS.tar.gz)
Done!

**Comment by LinusDierheimer** [comment]
Thats unfortunate, it is exactly the same as the one Ubuntu ships. I will look into a way to differentiate them. Neofetch does this by looking at the installed packages, and tbh i am not happy with that.

**Comment by LinusDierheimer** [comment]
Should be working on git master.

**Comment by LinusDierheimer** [comment]
I consider this one closed too.

**Comment by a2112670147** [comment]
在我的kubuntu2410上仍然显示Ubuntu，且升级2504之后依然显示Ubuntu，这显然不对，需要我提供什么吗？
On my Kubuntu 24.10, it still shows “Ubuntu”, and even after upgrading to 25.04 the label remains “Ubuntu”. This is obviously wrong. What information do you need me to provide?（The above English text was machine-translated from the preceding Chinese./）
